version: '3.7'
services:
  db:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_HOST: mysql
      MYSQL_DATABASE: users
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_USER: root
    volumes:
      - type: bind
        source: ./src/user/docker-entrypoint-initdb.d
        target: /docker-entrypoint-initdb.d
    ports:
    - "3306:3306"
  adminer:
    image: adminer
    restart: always
    ports:
      - "1234:8080"
