version: '3.7'
services:
  app:
    build: ./src/user-manager
    ports:
      - "3002:80"
    depends_on:
      - api
  api:
    build: ./src/user
    environment:
      APP_PORT: '3003'
      APP_HOST: '0.0.0.0'
      MYSQL_HOST: mysql
      MYSQL_DATABASE: users
      MYSQL_PASSWORD: root
      MYSQL_USER: root
    ports:
      - "3003:3003"
    depends_on:
      - mysql
    command: ["sh", "-c", "./wait-for-mysql.sh mysql && npm run migrations && npm run seeds && npm start"]
  mysql:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - type: bind
        source: ./src/user/docker-entrypoint-initdb.d
        target: /docker-entrypoint-initdb.d
    ports:
    - "3306:3306"
  adminer:
    image: adminer
    restart: always
    ports:
      - "1234:8080"
