// This is basically definitions of communcation between API and AMQP, in real life this should be wayyy smarter
module.exports = {
  ERRORS: {
    REQUEST_TOPIC: 'USERS_ERRORS_REQ',
    REQUEST_QUEUE: 'USERS_ERRORS_REQ_Q',
    RESPONSE_TOPIC: 'USERS_ERRORS_RES',
    RESPONSE_QUEUE: 'USERS_ERRORS_RES_Q',
  },
  INSERT_USER: {
    REQUEST_TOPIC: 'USERS_INSERT_REQ',
    REQUEST_QUEUE: 'USERS_INSERT_REQ_Q',
    RESPONSE_TOPIC: 'USERS_INSERT_RES',
    RESPONSE_QUEUE: 'USERS_INSERT_RES_Q',
  },
  FIND_ONE_USER: {
    REQUEST_TOPIC: 'USERS_FIND_ONE_REQ',
    REQUEST_QUEUE: 'USERS_FIND_ONE_REQ_Q',
    RESPONSE_TOPIC: 'USERS_FIND_ONE_RES',
    RESPONSE_QUEUE: 'USERS_FIND_ONE_RES_Q',
  },
  FIND_ALL_USERS: {
    REQUEST_TOPIC: 'USERS_FIND_ALL_REQ',
    REQUEST_QUEUE: 'USERS_FIND_ALL_REQ_Q',
    RESPONSE_TOPIC: 'USERS_FIND_ALL_RES',
    RESPONSE_QUEUE: 'USERS_FIND_ALL_RES_Q',
  },
  DESTROY_USER: {
    REQUEST_TOPIC: 'USERS_DESTROY_REQ',
    REQUEST_QUEUE: 'USERS_DESTROY_REQ_Q',
    RESPONSE_TOPIC: 'USERS_DESTROY_RES',
    RESPONSE_QUEUE: 'USERS_DESTROY_RES_Q',
  },
}
