// This is basically definitions of communcation between API and AMQP, in real life this should be wayyy smarter
module.exports = {
  ERRORS: {
    EXCHANGE: 'USERS_ERRORS',
    REQUEST: 'USERS_ERRORS_REQ',
    RESPONSE: 'USERS_ERRORS_RES',
    ROUTING_KEYS: {}
  },
  INSERT_USER: {
    EXCHANGE: 'USERS_INSERT',
    REQUEST: 'USERS_INSERT_REQ',
    RESPONSE: 'USERS_INSERT_RES',
    ROUTING_KEYS: {}
  },
  FIND_ONE_USER: {
    EXCHANGE: 'USERS_FIND_ONE',
    REQUEST: 'USERS_FIND_ONE_REQ',
    RESPONSE: 'USERS_FIND_ONE_RES',
    ROUTING_KEYS: {}
  },
  FIND_ALL_USERS: {
    EXCHANGE: 'USERS_FIND_ALL',
    REQUEST: 'USERS_FIND_ALL_REQ',
    RESPONSE: 'USERS_FIND_ALL_RES',
    ROUTING_KEYS: {}
  },
  DESTROY_USER: {
    EXCHANGE: 'USERS_DESTROY',
    REQUEST: 'USERS_DESTROY_REQ',
    RESPONSE: 'USERS_DESTROY_RES',
    ROUTING_KEYS: {}
  },
}
